"""
Utility to write RNA structures to PDB format for visualization.
"""
import numpy as np
from pathlib import Path


def write_pdb(coords: np.ndarray, output_path: str, sequence: str = None):
    """
    Write C1' coordinates to PDB file.

    Args:
        coords: (L, 3) array of C1' coordinates in Angstroms
        output_path: Output PDB file path
        sequence: RNA sequence (optional, defaults to 'A' for all)
    """
    L = len(coords)

    if sequence is None:
        sequence = 'A' * L

    # Nucleotide name mapping
    nuc_map = {'A': 'A', 'C': 'C', 'G': 'G', 'U': 'U', 'T': 'U'}

    with open(output_path, 'w') as f:
        f.write("REMARK   Generated by RNA folding model\n")
        f.write("REMARK   C1' atoms only\n")

        for i, (x, y, z) in enumerate(coords):
            res_name = nuc_map.get(sequence[i].upper(), 'A')
            # PDB format: ATOM, serial, name, resName, chainID, resSeq, x, y, z
            f.write(f"ATOM  {i+1:5d}  C1' {res_name:>3} A{i+1:4d}    "
                   f"{x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00           C\n")

        f.write("END\n")

    print(f"Wrote PDB to {output_path}")


if __name__ == "__main__":
    # Test with linear example
    test_coords = np.array([
        [ 4.4280739,  0.00360466, -0.041538015],
        [ 3.7382195,  2.3700111,   1.2735695],
        [ 1.8609965,  4.0093365,   2.4314771],
        [-0.58877432, 4.3511987,   3.7392466],
        [-2.8422990,  3.3880467,   4.9414272]
    ])

    write_pdb(test_coords, "test_linear.pdb", sequence="AUGCA")
    print("Test PDB created: test_linear.pdb")
